# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: postgresql
  encoding: unicode
  database: booking_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: booking_test
  pool: 5
  timeout: 5000

